apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: register-app1 
spec:
  selector:
    app: register-app1

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
